version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    groups: "applies-to version-updates"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "MiJur"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    groups: "applies-to security-updates"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "MiJur"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "MiJur"
    commit-message:
      prefix: "ci"
